CREATE TABLE IF NOT EXISTS LOTACAO
(
  ID              LONG      NOT NULL PRIMARY KEY,
  DATA_INICIAL    TIMESTAMP NOT NULL,
  DATA_FINAL      TIMESTAMP NOT NULL,
  CARGO_ID        LONG      NOT NULL,
  DEPARTAMENTO_ID LONG      NOT NULL,
  FUNCIONARIO_ID  LONG      NOT NULL
)